### ISSUE TITLE
Bad Trigger for RAILS_DEFAULT_LOGGER.debug

### ISSUE THREAD

**Issue by JEG2** [drnic/ruby-on-rails-tmbundle#12]
This is just a minor nitpick, but rdb makes me think of a database, not the logger.  Maybe logdd for "logger default debug" is better, though I realize it's mostly made up.  Just a thought.

**Comment by drnic** [comment]
Fair point.

**Comment by drnic** [comment]
Ok, it's now: Rails.logger.debug "${1:message}" with the tab 'deb'. Sound good?

**Comment by JEG2** [comment]
Works for me.
