### ISSUE TITLE
Invalid Multibyte Character

### ISSUE THREAD

**Issue by conradwt** [drnic/ruby-on-rails-tmbundle#14]
I recently started seeing the following issue when I tried to create a partial from the selected text (i.e. Control-Shift-H): 

 /Users/conradwt/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/create_partial_from_selection.rb:17: invalid multibyte char (US-ASCII)
/Users/conradwt/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/create_partial_from_selection.rb:17: invalid multibyte char (US-ASCII)
/Users/conradwt/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/create_partial_from_selection.rb:17: syntax error, unexpected $end, expecting ')'
...Mate.exit_show_tool_tip("The ‘create partial from selectio...
...                               ^

Lastly, I have the following configuration:

Mac OS 10.5.8
ruby 1.9.2dev (2010-02-20 trunk 26717) [powerpc-darwin9.8.0]
Rails 2.3.5

**Comment by drnic** [comment]
I think this issue might be in TextMate's own Support/lib files.

This bug is from the line:

```
TextMate.exit_show_tool_tip("The ‘create partial from selection’ action works within view files only.")
```

Are you using TextMate version 1.5.9 (1589)? If not, turn on Cutting Edge and do an update. Did that help?

If not, raise a bug with TextMate itself. Not sure where that is. Perhaps start with ##textmate irc channel.

**Comment by Stefano1990** [comment]
I had the same problem. Turning on cutting edge did the trick for me. Thx, drnic.

**Comment by dmclark** [comment]
This may work in 10.5, bud for the life of me I  cant get  it to work in 10.6

i'm getting errors when trying to use comands from the rails bundle. likei:
/Library/Application Support/TextMate/Bundles/Ruby on
Rails.tmbundle/Support/bin/create_partial_from_selection.rb:17:
invalid multibyte char (US-ASCII)
/Library/Application Support/TextMate/Bundles/Ruby on
Rails.tmbundle/Support/bin/create_partial_from_selection.rb:17:
invalid multibyte char (US-ASCII)
/Library/Application Support/TextMate/Bundles/Ruby on
Rails.tmbundle/Support/bin/create_partial_from_selection.rb:17: syntax
error, unexpected $end, expecting ')'
...Mate.exit_show_tool_tip("The ‘create partial from selectio...
...                               ^

I  am using latest edge, so
http://github.com/drnic/ruby-on-rails-tmbundle/issues/issue/14 isn't
it.

my ruby_path his /Users/Administrator/.rvm/bin/textmate_ruby

**Comment by Stefano1990** [comment]
if with 10.5 you are refering to the OS, I am running 10.6.4 and textmate 1.5.9.
And as I said, edge did it for me.

**Comment by dmclark** [comment]
yes, I  did mean os 10.6.4. I  made that distinction because the original poster had "Mac OS 10.5.8"

this is driving me nuts - any ideas?

**Comment by jmonster** [comment]
For me, this problem was caused by the TM_RUBY variable (for use with RVM). I just removed it for now...

**Comment by dmclark** [comment]
thanks jmonster, that did the trick

**Comment by jmonster** [comment]
I haven't tried it, but I just noticed that http://rvm.beginrescueend.com/integration/textmate/ states that you need version >= 0.1.45 for proper TextMate compatibility. I was running 0.1.43; my guess is you have an older version too? The TM_RUBY variable is probably ok once you update.

**Comment by justinperkins** [comment]
I am running ruby 1.9.2p0 (no rvm) and getting this error as well. I thought it was because the encoding declaration was missing from the ruby files in /Support/bin but that didn't fix the issue for me. I have cutting edge TM turned on and am running the latest (1.5.9 (1589)).

**Comment by dan-dyomo** [comment]
Hi, I'm having a problem with Create Partial from Selection as well.

The error message I'm seeing (which appears where my selected text used to be) is:

/Applications/TextMate.app/Contents/SharedSupport/Support/lib/ui.rb:355:in `to_plist': An object in the argument tree could not be converted (ArgumentError)
    from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/ui.rb:355:in`request_string_core'
    from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/ui.rb:193:in `request_string'
    from /Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/create_partial_from_selection.rb:23:in`<main>' 

I'm running rvm 1.0.5 set for ruby 1.9.2.  I've followed all the instructions here and in the rvm textmate integration page.

I'm guessing that the problem is that I'm not running the right version of textmate.  The release I'm running is 1.5.9 (1510).  I've tried to use the update feature, but I'm getting a 500 error.  Any suggestions?

**Comment by JerryWho** [comment]
I tried it with TM_RUBY and setting it to different versions of rubies via rvm.
(rvm wrapper VERSION textmate see http://rvm.beginrescueend.com/integration/textmate/)

As I can see everything is okay, when using ruby 1.8.7. Just when using ruby 1.9.x the error occurs.

**Comment by armanddp** [comment]
@dan-dyomo the following article was a life saver for me getting around the errors you getting : http://gnuu.org/2009/05/25/getting-gittmbundle-working-with-ruby19/

**Comment by justinperkins** [comment]
Several of the rails-y partials in this bundle have multibyte characters, such as ellipsis, but the encoding is not correctly specified. See Support/app/views/annotate/_content.html.erb

**Comment by justinperkins** [comment]
Sorry guys, commented on the wrong bundle. My last comment was intended for the git bundle.

**Comment by b-mandelbrot** [comment]
Yes. I used rvm wrapper ruby-1.8.7@foobar textmate ! works fine to me! The problem is ruby 1.9.2 i think.

**Comment by Bodacious** [comment]
Hi all

I'm still seeing this error in 1.9.2

What's the latest on this issue?

Thanks
