### ISSUE TITLE
Invalid XML in a tmSnippet

### ISSUE THREAD

**Issue by sorbits** [drnic/ruby-on-rails-tmbundle#17]
Commit 7116f14 broke the file `Snippets/Create sweeper class.tmSnippet` (it is no longer valid XML).

A fix is available here sorbits/ruby-on-rails-tmbundle@39a5ff4f71efbf1cf8f510fe02901d73d6564973

**Comment by infininight** [comment]
Fixed by cc21f9881e569ea9b49f6c0e92b91ece72a86d0f
