### ISSUE TITLE
Support/lib/rails/generate.rb method find_generator_names does not appear to return a list

### ISSUE THREAD

**Issue by tomPorter** [drnic/ruby-on-rails-tmbundle#3]
When I issue shift-ctl-pipe and pick the generate option(1) I only see the standard generators listed in known_generators.  Looks like find_generator_names returns an empty list.

How do I run the tests supplied with the bundle?

mac os x 10.6 RoR bundle from git,

**Comment by tomPorter** [comment]
results of running test:

/Users/tporter/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/test
tporter@tinnie:test (master)> ruby test_generator.rb 
Loaded suite test_generator
Started
EE.
Finished in 0.000583 seconds.

  1) Error:
test_find_generator_names(TestBinGenerate):
NameError: uninitialized constant Generator::RailsPath
    ./../lib/rails/generate.rb:39:in `find_generator_names'
    test_generator.rb:12:in`test_find_generator_names'

  2) Error:
test_generators(TestBinGenerate):
NameError: uninitialized constant Generator::RailsPath
    ./../lib/rails/generate.rb:39:in `find_generator_names'
    ./../lib/rails/generate.rb:30:in`setup_generators'
    test_generator.rb:21:in `test_generators'

3 tests, 1 assertions, 0 failures, 2 errors

**Comment by drnic** [comment]
I have a feeling this has been broken for a long time. 

Eww, this will also be a pain for rails3 support with it's new generator system.

Nonetheless, it'd be great to have it working.

**Comment by drnic** [comment]
Ok, first things first, test_generate.rb is now working.

**Comment by drnic** [comment]
Ok, now it is finding all the non-standard generators again (NOTE: must remove Builder.rb from /Applications/TextMate.app/Contents/SharedSupport/Support/lib - there is another ticket to fix this bug)
