### ISSUE TITLE
"Install Plugin" does not work (OSX 10.6.2 - Textmate 1.5.9 (1510) - ruby 1.8.7 (2009-06-12 patchlevel 174) [i686-darwin10.0.0]

### ISSUE THREAD

**Issue by i0n** [drnic/ruby-on-rails-tmbundle#4]
Hi there. 

Apologies if this has been documented somewhere else, but if it has it's not immediately apparent.
When trying to run "install plugin" I get the following error:

/usr/local/lib/ruby/1.8/erb.rb:354:in `trim_line2': private method`scan' called for # (NoMethodError) from /usr/local/lib/ruby/1.8/erb.rb:311:in `call' from /usr/local/lib/ruby/1.8/erb.rb:311:in`scan' from /usr/local/lib/ruby/1.8/erb.rb:500:in `compile' from /usr/local/lib/ruby/1.8/erb.rb:668:in`initialize' from /Users/i0n/Library/Application Support/TextMate/Pristine Copy/Bundles/Ruby on Rails.tmbundle/Support/bin/list_plugins.rb:42:in `new' from /Users/i0n/Library/Application Support/TextMate/Pristine Copy/Bundles/Ruby on Rails.tmbundle/Support/bin/list_plugins.rb:42

I've tried various things including setting the TM_RUBY and TM_BUNDLE_SUPPORT variables without any luck. Am I alone in this error, or is this something that is affecting others?

**Comment by mrichman** [comment]
I get this error:

/Applications/TextMate.app/Contents/SharedSupport/Support/lib/osx/plist.bundle: dlopen(/Applications/TextMate.app/Contents/SharedSupport/Support/lib/osx/plist.bundle, 9): no suitable image found. Did find: (LoadError) /Applications/TextMate.app/Contents/SharedSupport/Support/lib/osx/plist.bundle: no matching architecture in universal wrapper - /Applications/TextMate.app/Contents/SharedSupport/Support/lib/osx/plist.bundle from /Applications/TextMate.app/Contents/SharedSupport/Support/lib/textmate.rb:2 from /Users/mark/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/lib/rails_bundle_tools.rb:12:in `require' from /Users/mark/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/lib/rails_bundle_tools.rb:12 from /Users/mark/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/list_plugins.rb:20:in`require' from /Users/mark/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/list_plugins.rb:20

**Comment by drnic** [comment]
@mrichman - I'm not sure what dlopen is, or where it got built from, but my guess is you need to reinstall something after upgrading to Snow Leopard?

**Comment by drnic** [comment]
@i0n - god I hate the textmate stack traces :/

Are people still installing plugins a lot, do you think? Can we deprecate/remote "Install Plugin"?

**Comment by drnic** [comment]
Ok, I've fixed the initial bug (incorrect use of ERB.new api) but the basic Install Plugin widget itself doesn't work. I don't really feel like "fixing" it, since it relies on the http://agilewebdevelopment.com/plugins/search API, which is no longer the canonical source of Rails extensions (which are more and more bundled as gems). It is also written with JavaScript but without any JS tests.

I'm going to remove the Install Plugins code. I'll do it all in one commit so it can be reversed if anyone gets really cranky.
