### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by kendogprior** [drnic/ruby-on-rails-tmbundle#5]
All keyboard shortcuts work fine for me except when the file being edited is a template(i.e. .html.erb) file. Code snippets can be inserted with the menu options but not when using the keyboard. Is this a bundle problem, a Textmate problem or maybe I'm not doing something right. I feel sure this did work once. I have raised this problem with Textmate. MY OS  is Snow Leopard, my textmate version is 1.5.9(1510).

**Comment by kendogprior** [comment]
This a comment to my own issue. Being a newbie to TextMate I have only just discovered that the Bundles editor for RoR has a 'scope selector' for the keyboard shortcuts. For the html.erb files it seems the scope should be set to 'source.ruby.rails'. This seemed odd to me  but at least it allowed the keyboard shortcuts to work. Is there a quick way to change all the  selectors that are relevant to views?

**Comment by drnic** [comment]
Yep, common annoyance - the grammar/scope/syntax isn't what you think it is.
