### ISSUE TITLE
HTML(Rails)  <% %>  Error

### ISSUE THREAD

**Issue by slimGap** [drnic/ruby-on-rails-tmbundle#6]
When using HTML(Rails) and using the command 'shift-ctrl + >' to get <% %>.

```
/tmp/temp_textmate.VbVhwa:19:in /bin/bash: -c: line 0: unexpected EOF while looking for matching `''
/bin/bash: -c: line 1: syntax error: unexpected end of fileto_a' for "<%=  %>":String (NoMethodError)
```

I get <%= %> ok, but then I get the above error on the attempt to change it to <% %>
This is with the latest tmbundle, ruby 1.9.1 and rails 2.3.4

**Comment by drnic** [comment]
The 'Toggle ERb Tags' command is in the Ruby.tmbundle (sorry). I think issues for this bundle go here: http://github.com/textmate/ruby.tmbundle/issues
