### ISSUE TITLE
Rake tasks do not work (stack too deep) - Solution Within

### ISSUE THREAD

**Issue by igoodrich** [drnic/ruby-on-rails-tmbundle#7]
On latest versions (as of 12/3/2009) of both textmate and ruby-on-rails-tmbundle, rake tasks, including anything with Ctrl-\, do not work.  These same tasks work fine from the command line.

If you turn on tracing, you see that the problem is the Builder.rb in /Applications/TextMate.app/Contents/SharedSupport/Support/lib
If you go the line number at the top of the trace, you'll notice some less than tasty monkey-patching into Kernel and Object.  My guess is -- though I'm new to ruby -- that the name "blank_slate_method_added" was already patched by some other library to Object (maybe not Kernel).  Hence, the fix (which properly is a TextMate fix) is to rename the alias.  Somewhat goofily, I chose "my_blank_slate_method_added" as so:

```
module Kernel
  class << self
    alias_method :my_blank_slate_method_added, :method_added
    def method_added(name)
      my_blank_slate_method_added(name)
      return if self != Kernel
      Builder::BlankSlate.hide(name)
    end
  end
end

class Object
  class << self
    alias_method :my_blank_slate_method_added, :method_added
    def method_added(name)
      my_blank_slate_method_added(name)
      return if self != Object
      Builder::BlankSlate.hide(name)
    end
  end
end
```

**Comment by drnic** [comment]
I hate the builder.rb issue. The common solution is to remove it from TextMate's Support source; but each new TM version reintroduces it.

I'll investigate your fix as this is just annoying.

**Comment by drnic** [comment]
Are you putting this code in your TM bundle? or your rails app?

**Comment by drnic** [comment]
I think I've fixed the Builder.rb issue. I've put a dummy Builder.rb in the tmbundle to appear at the start of the $LOAD_PATH. I _think_ it is fixing the bug. 

Can you confirm that everything works for you?

**Comment by drnic** [comment]
I'm going to claim this is now fixed. Reopen it if you'd like.
