### ISSUE TITLE
Create Partial From Selection error

### ISSUE THREAD

**Issue by imjma** [drnic/ruby-on-rails-tmbundle#9]
/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/create_partial_from_selection.rb:17: invalid multibyte char (US-ASCII)
/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/create_partial_from_selection.rb:17: invalid multibyte char (US-ASCII)
/Library/Application Support/TextMate/Bundles/Ruby on Rails.tmbundle/Support/bin/create_partial_from_selection.rb:17: syntax error, unexpected $end, expecting ')'
...Mate.exit_show_tool_tip("The ‘create partial from selectio...
...                               ^

not only this one, also some of others I also got this error message

**Comment by drnic** [comment]
Which version of ruby are you using? (btw, I use this snippet and it works for me so let's figure out where the diff is)

**Comment by drnic** [comment]
Are you using ruby19? There is another issue raised for this issue by a ruby19 user

**Comment by imjma** [comment]
Yes, I am using ruby 1.9 ...

**Comment by drnic** [comment]
Ok, I'll close this one and make #14 the sole ticket for this issue
